version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: flask run --host=0.0.0.0 --port=8000 --debug --reload
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"